CREATE DATABASE my_app_database;


USE my_app_database;


CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first VARCHAR(50) NOT NULL UNIQUE,
    last VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);